// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1n6_grvAdi1mVMtXHOD_TWjvVvnT2JpQ',
    appId: '1:720656502926:web:f2685840b3454035ca39df',
    messagingSenderId: '720656502926',
    projectId: 'wpi-parking-app',
    authDomain: 'wpi-parking-app.firebaseapp.com',
    storageBucket: 'wpi-parking-app.appspot.com',
    measurementId: 'G-VNTZH42EJ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuN01Q_4_MWNXISWiPR_hOVnLfeMDzopE',
    appId: '1:720656502926:android:26d2d9004928f0c1ca39df',
    messagingSenderId: '720656502926',
    projectId: 'wpi-parking-app',
    storageBucket: 'wpi-parking-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1WtrqEmzWLrZtCS_1gK142hzDZZaUc0M',
    appId: '1:720656502926:ios:0ad7e32d2d2a9ba6ca39df',
    messagingSenderId: '720656502926',
    projectId: 'wpi-parking-app',
    storageBucket: 'wpi-parking-app.appspot.com',
    iosClientId: '720656502926-sei22toklfhb8213nsb8itbdptp6q737.apps.googleusercontent.com',
    iosBundleId: 'com.example.parking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1WtrqEmzWLrZtCS_1gK142hzDZZaUc0M',
    appId: '1:720656502926:ios:0ad7e32d2d2a9ba6ca39df',
    messagingSenderId: '720656502926',
    projectId: 'wpi-parking-app',
    storageBucket: 'wpi-parking-app.appspot.com',
    iosClientId: '720656502926-sei22toklfhb8213nsb8itbdptp6q737.apps.googleusercontent.com',
    iosBundleId: 'com.example.parking',
  );
}
